[package]
name = "video_capture"
version = "0.1.0"
authors = ["koukemo <java.sparrow22.surface@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.83.0"
